/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif

#define SWIG_DIRECTORS


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_v8(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_v8(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_v8(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that C# proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif
#include <string>
#include <exception>

namespace Swig {
  /* Director base class - not currently used in C# directors */
  class Director {
  };

  /* Base class for director exceptions */
  class DirectorException : public std::exception {
  protected:
    std::string swig_msg;

  public:
    DirectorException(const char *msg) : swig_msg(msg) {
    }

    DirectorException(const std::string &msg) : swig_msg(msg) {
    }

    virtual ~DirectorException() throw() {
    }

    const char *what() const throw() {
      return swig_msg.c_str();
    }
  };

  /* Pure virtual method exception */
  class DirectorPureVirtualException : public DirectorException {
  public:
    DirectorPureVirtualException(const char *msg) : DirectorException(std::string("Attempt to invoke pure virtual method ") + msg) {
    }
  };
}


#include "V8Simple.h"


#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>

SWIGINTERN std::vector< V8Simple::String > *new_std_vector_Sl_V8Simple_String_Sg___SWIG_2(int capacity){
        std::vector< V8Simple::String >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< V8Simple::String >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN V8Simple::String std_vector_Sl_V8Simple_String_Sg__getitemcopy(std::vector< V8Simple::String > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN V8Simple::String const &std_vector_Sl_V8Simple_String_Sg__getitem(std::vector< V8Simple::String > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__setitem(std::vector< V8Simple::String > *self,int index,V8Simple::String const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__AddRange(std::vector< V8Simple::String > *self,std::vector< V8Simple::String > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< V8Simple::String > *std_vector_Sl_V8Simple_String_Sg__GetRange(std::vector< V8Simple::String > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< V8Simple::String >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__Insert(std::vector< V8Simple::String > *self,int index,V8Simple::String const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__InsertRange(std::vector< V8Simple::String > *self,int index,std::vector< V8Simple::String > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__RemoveAt(std::vector< V8Simple::String > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__RemoveRange(std::vector< V8Simple::String > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< V8Simple::String > *std_vector_Sl_V8Simple_String_Sg__Repeat(V8Simple::String const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< V8Simple::String >(count, value);
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__Reverse__SWIG_0(std::vector< V8Simple::String > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__Reverse__SWIG_1(std::vector< V8Simple::String > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_V8Simple_String_Sg__SetRange(std::vector< V8Simple::String > *self,int index,std::vector< V8Simple::String > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN std::vector< V8Simple::Value * > *new_std_vector_Sl_V8Simple_Value_Sm__Sg___SWIG_2(int capacity){
        std::vector< V8Simple::Value * >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< V8Simple::Value * >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN V8Simple::Value *std_vector_Sl_V8Simple_Value_Sm__Sg__getitemcopy(std::vector< V8Simple::Value * > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN V8Simple::Value *const &std_vector_Sl_V8Simple_Value_Sm__Sg__getitem(std::vector< V8Simple::Value * > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__setitem(std::vector< V8Simple::Value * > *self,int index,V8Simple::Value *const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__AddRange(std::vector< V8Simple::Value * > *self,std::vector< V8Simple::Value * > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< V8Simple::Value * > *std_vector_Sl_V8Simple_Value_Sm__Sg__GetRange(std::vector< V8Simple::Value * > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< V8Simple::Value * >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__Insert(std::vector< V8Simple::Value * > *self,int index,V8Simple::Value *const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__InsertRange(std::vector< V8Simple::Value * > *self,int index,std::vector< V8Simple::Value * > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__RemoveAt(std::vector< V8Simple::Value * > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__RemoveRange(std::vector< V8Simple::Value * > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< V8Simple::Value * > *std_vector_Sl_V8Simple_Value_Sm__Sg__Repeat(V8Simple::Value *const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< V8Simple::Value * >(count, value);
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__Reverse__SWIG_0(std::vector< V8Simple::Value * > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__Reverse__SWIG_1(std::vector< V8Simple::Value * > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_V8Simple_Value_Sm__Sg__SetRange(std::vector< V8Simple::Value * > *self,int index,std::vector< V8Simple::Value * > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN bool std_vector_Sl_V8Simple_Value_Sm__Sg__Contains(std::vector< V8Simple::Value * > *self,V8Simple::Value *const &value){
        return std::find(self->begin(), self->end(), value) != self->end();
      }
SWIGINTERN int std_vector_Sl_V8Simple_Value_Sm__Sg__IndexOf(std::vector< V8Simple::Value * > *self,V8Simple::Value *const &value){
        int index = -1;
        std::vector< V8Simple::Value * >::iterator it = std::find(self->begin(), self->end(), value);
        if (it != self->end())
          index = (int)(it - self->begin());
        return index;
      }
SWIGINTERN int std_vector_Sl_V8Simple_Value_Sm__Sg__LastIndexOf(std::vector< V8Simple::Value * > *self,V8Simple::Value *const &value){
        int index = -1;
        std::vector< V8Simple::Value * >::reverse_iterator rit = std::find(self->rbegin(), self->rend(), value);
        if (rit != self->rend())
          index = (int)(self->rend() - 1 - rit);
        return index;
      }
SWIGINTERN bool std_vector_Sl_V8Simple_Value_Sm__Sg__Remove(std::vector< V8Simple::Value * > *self,V8Simple::Value *const &value){
        std::vector< V8Simple::Value * >::iterator it = std::find(self->begin(), self->end(), value);
        if (it != self->end()) {
          self->erase(it);
	  return true;
        }
        return false;
      }


/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "V8Simple_wrap.h"

SwigDirector_Callback::SwigDirector_Callback() : V8Simple::Callback(), Swig::Director() {
  swig_init_callbacks();
}

V8Simple::Type SwigDirector_Callback::GetValueType() const {
  V8Simple::Type c_result = SwigValueInit< V8Simple::Type >() ;
  int jresult = 0 ;
  
  if (!swig_callbackGetValueType) {
    return V8Simple::Callback::GetValueType();
  } else {
    jresult = (int) swig_callbackGetValueType();
    c_result = (V8Simple::Type)jresult; 
  }
  return c_result;
}

SwigDirector_Callback::~SwigDirector_Callback() {
  
}


void SwigDirector_Callback::Delete() {
  V8Simple::Value::Delete();
}

V8Simple::Value *SwigDirector_Callback::Call(V8Simple::UniqueValueVector *args) {
  V8Simple::Value *c_result = 0 ;
  void * jresult = 0 ;
  void * jargs = 0 ;
  
  if (!swig_callbackCall) {
    return V8Simple::Callback::Call(args);
  } else {
    jargs = (void *) args; 
    jresult = (void *) swig_callbackCall(jargs);
    c_result = (V8Simple::Value *)jresult; 
  }
  return c_result;
}

void SwigDirector_Callback::Retain() {
  if (!swig_callbackRetain) {
    V8Simple::Callback::Retain();
    return;
  } else {
    swig_callbackRetain();
  }
}

void SwigDirector_Callback::Release() {
  if (!swig_callbackRelease) {
    V8Simple::Callback::Release();
    return;
  } else {
    swig_callbackRelease();
  }
}

void SwigDirector_Callback::swig_connect_director(SWIG_Callback0_t callbackGetValueType, SWIG_Callback1_t callbackCall, SWIG_Callback2_t callbackRetain, SWIG_Callback3_t callbackRelease) {
  swig_callbackGetValueType = callbackGetValueType;
  swig_callbackCall = callbackCall;
  swig_callbackRetain = callbackRetain;
  swig_callbackRelease = callbackRelease;
}

void SwigDirector_Callback::swig_init_callbacks() {
  swig_callbackGetValueType = 0;
  swig_callbackCall = 0;
  swig_callbackRetain = 0;
  swig_callbackRelease = 0;
}

SwigDirector_MessageHandler::SwigDirector_MessageHandler() : V8Simple::MessageHandler(), Swig::Director() {
  swig_init_callbacks();
}

void SwigDirector_MessageHandler::Handle(V8Simple::String const *message) {
  void * jmessage = 0 ;
  
  if (!swig_callbackHandle) {
    V8Simple::MessageHandler::Handle(message);
    return;
  } else {
    jmessage = (void *) message; 
    swig_callbackHandle(jmessage);
  }
}

SwigDirector_MessageHandler::~SwigDirector_MessageHandler() {
  
}


void SwigDirector_MessageHandler::swig_connect_director(SWIG_Callback0_t callbackHandle) {
  swig_callbackHandle = callbackHandle;
}

void SwigDirector_MessageHandler::swig_init_callbacks() {
  swig_callbackHandle = 0;
}

SwigDirector_ScriptExceptionHandler::SwigDirector_ScriptExceptionHandler() : V8Simple::ScriptExceptionHandler(), Swig::Director() {
  swig_init_callbacks();
}

void SwigDirector_ScriptExceptionHandler::Handle(V8Simple::ScriptException &e) {
  void * je = 0 ;
  
  if (!swig_callbackHandle) {
    V8Simple::ScriptExceptionHandler::Handle(e);
    return;
  } else {
    je = (V8Simple::ScriptException *) &e; 
    swig_callbackHandle(je);
  }
}

SwigDirector_ScriptExceptionHandler::~SwigDirector_ScriptExceptionHandler() {
  
}


void SwigDirector_ScriptExceptionHandler::swig_connect_director(SWIG_Callback0_t callbackHandle) {
  swig_callbackHandle = callbackHandle;
}

void SwigDirector_ScriptExceptionHandler::swig_init_callbacks() {
  swig_callbackHandle = 0;
}

SwigDirector_ExternalFreer::SwigDirector_ExternalFreer() : V8Simple::ExternalFreer(), Swig::Director() {
  swig_init_callbacks();
}

void SwigDirector_ExternalFreer::Free(void *external) {
  void * jexternal = 0 ;
  
  if (!swig_callbackFree) {
    V8Simple::ExternalFreer::Free(external);
    return;
  } else {
    jexternal = (void *) external; 
    swig_callbackFree(jexternal);
  }
}

SwigDirector_ExternalFreer::~SwigDirector_ExternalFreer() {
  
}


void SwigDirector_ExternalFreer::swig_connect_director(SWIG_Callback0_t callbackFree) {
  swig_callbackFree = callbackFree;
}

void SwigDirector_ExternalFreer::swig_init_callbacks() {
  swig_callbackFree = 0;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_Value_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Value *arg1 = (V8Simple::Value *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Value *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Value const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Value(void * jarg1) {
  V8Simple::Value *arg1 = (V8Simple::Value *) 0 ;
  
  arg1 = (V8Simple::Value *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_String_New(unsigned char* jarg1, int jarg2) {
  void * jresult ;
  V8Simple::byte *arg1 = (V8Simple::byte *) 0 ;
  int arg2 ;
  V8Simple::String *result = 0 ;
  
  arg1 = jarg1;
  arg2 = (int)jarg2; 
  result = (V8Simple::String *)V8Simple::String::New((unsigned char const *)arg1,arg2);
  jresult = (void *)result; 
  
  
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_String__SWIG_0(unsigned char* jarg1, int jarg2) {
  void * jresult ;
  V8Simple::byte *arg1 = (V8Simple::byte *) 0 ;
  int arg2 ;
  V8Simple::String *result = 0 ;
  
  arg1 = jarg1;
  arg2 = (int)jarg2; 
  result = (V8Simple::String *)new V8Simple::String((V8Simple::byte const *)arg1,arg2);
  jresult = (void *)result; 
  
  
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_String__SWIG_1(void * jarg1) {
  void * jresult ;
  V8Simple::String *arg1 = 0 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (V8Simple::String *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::String const & type is null", 0);
    return 0;
  } 
  result = (V8Simple::String *)new V8Simple::String((V8Simple::String const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_String_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::String *arg1 = (V8Simple::String *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::String *)jarg1; 
  result = (V8Simple::Type)((V8Simple::String const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_String_GetBuffer(void * jarg1, unsigned char* jarg2) {
  V8Simple::String *arg1 = (V8Simple::String *) 0 ;
  V8Simple::byte *arg2 = (V8Simple::byte *) 0 ;
  
  arg1 = (V8Simple::String *)jarg1; 
  arg2 = jarg2;
  ((V8Simple::String const *)arg1)->GetBuffer(arg2);
  
  
}


SWIGEXPORT int SWIGSTDCALL CSharp_String_GetBufferLength(void * jarg1) {
  int jresult ;
  V8Simple::String *arg1 = (V8Simple::String *) 0 ;
  int result;
  
  arg1 = (V8Simple::String *)jarg1; 
  result = (int)((V8Simple::String const *)arg1)->GetBufferLength();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_String(void * jarg1) {
  V8Simple::String *arg1 = (V8Simple::String *) 0 ;
  
  arg1 = (V8Simple::String *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_String_Copy(void * jarg1) {
  void * jresult ;
  V8Simple::String *arg1 = (V8Simple::String *) 0 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (V8Simple::String *)jarg1; 
  result = (V8Simple::String *)((V8Simple::String const *)arg1)->Copy();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Function_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Function *arg1 = (V8Simple::Function *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Function *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Function const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Function_Call(void * jarg1, void * jarg2) {
  void * jresult ;
  V8Simple::Function *arg1 = (V8Simple::Function *) 0 ;
  std::vector< V8Simple::Value * > *arg2 = 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Function *)jarg1; 
  arg2 = (std::vector< V8Simple::Value * > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return 0;
  } 
  result = (V8Simple::Value *)(arg1)->Call((std::vector< V8Simple::Value * > const &)*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Function_Construct(void * jarg1, void * jarg2) {
  void * jresult ;
  V8Simple::Function *arg1 = (V8Simple::Function *) 0 ;
  std::vector< V8Simple::Value * > *arg2 = 0 ;
  V8Simple::Object *result = 0 ;
  
  arg1 = (V8Simple::Function *)jarg1; 
  arg2 = (std::vector< V8Simple::Value * > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return 0;
  } 
  result = (V8Simple::Object *)(arg1)->Construct((std::vector< V8Simple::Value * > const &)*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Function_StrictEquals(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  V8Simple::Function *arg1 = (V8Simple::Function *) 0 ;
  V8Simple::Function *arg2 = (V8Simple::Function *) 0 ;
  bool result;
  
  arg1 = (V8Simple::Function *)jarg1; 
  arg2 = (V8Simple::Function *)jarg2; 
  result = (bool)(arg1)->StrictEquals((V8Simple::Function const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Function(void * jarg1) {
  V8Simple::Function *arg1 = (V8Simple::Function *) 0 ;
  
  arg1 = (V8Simple::Function *)jarg1; 
  delete arg1;
}


SWIGEXPORT int SWIGSTDCALL CSharp_UniqueValueVector_Length(void * jarg1) {
  int jresult ;
  V8Simple::UniqueValueVector *arg1 = (V8Simple::UniqueValueVector *) 0 ;
  int result;
  
  arg1 = (V8Simple::UniqueValueVector *)jarg1; 
  result = (int)(arg1)->Length();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_UniqueValueVector_Get(void * jarg1, int jarg2) {
  void * jresult ;
  V8Simple::UniqueValueVector *arg1 = (V8Simple::UniqueValueVector *) 0 ;
  int arg2 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::UniqueValueVector *)jarg1; 
  arg2 = (int)jarg2; 
  result = (V8Simple::Value *)(arg1)->Get(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_UniqueValueVector(void * jarg1) {
  V8Simple::UniqueValueVector *arg1 = (V8Simple::UniqueValueVector *) 0 ;
  
  arg1 = (V8Simple::UniqueValueVector *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_UniqueValueVector_Delete(void * jarg1) {
  V8Simple::UniqueValueVector *arg1 = (V8Simple::UniqueValueVector *) 0 ;
  
  arg1 = (V8Simple::UniqueValueVector *)jarg1; 
  (arg1)->Delete();
}


SWIGEXPORT int SWIGSTDCALL CSharp_Object_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Object *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Object const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Object_Get(void * jarg1, void * jarg2) {
  void * jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Object *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  result = (V8Simple::Value *)(arg1)->Get((V8Simple::String const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Object_Set(void * jarg1, void * jarg2, void * jarg3) {
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  V8Simple::Value *arg3 = (V8Simple::Value *) 0 ;
  
  arg1 = (V8Simple::Object *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  arg3 = (V8Simple::Value *)jarg3; 
  (arg1)->Set((V8Simple::String const *)arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Object_Keys(void * jarg1) {
  void * jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::UniqueValueVector *result = 0 ;
  
  arg1 = (V8Simple::Object *)jarg1; 
  result = (V8Simple::UniqueValueVector *)(arg1)->Keys();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Object_InstanceOf(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::Function *arg2 = (V8Simple::Function *) 0 ;
  bool result;
  
  arg1 = (V8Simple::Object *)jarg1; 
  arg2 = (V8Simple::Function *)jarg2; 
  result = (bool)(arg1)->InstanceOf(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Object_CallMethod(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  std::vector< V8Simple::Value * > *arg3 = 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Object *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  arg3 = (std::vector< V8Simple::Value * > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return 0;
  } 
  result = (V8Simple::Value *)(arg1)->CallMethod((V8Simple::String const *)arg2,(std::vector< V8Simple::Value * > const &)*arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Object_ContainsKey(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  bool result;
  
  arg1 = (V8Simple::Object *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  result = (bool)(arg1)->ContainsKey((V8Simple::String const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Object_GetArrayBufferData(void * jarg1) {
  void * jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  void *result = 0 ;
  
  arg1 = (V8Simple::Object *)jarg1; 
  result = (void *)(arg1)->GetArrayBufferData();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Object_StrictEquals(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  V8Simple::Object *arg2 = (V8Simple::Object *) 0 ;
  bool result;
  
  arg1 = (V8Simple::Object *)jarg1; 
  arg2 = (V8Simple::Object *)jarg2; 
  result = (bool)(arg1)->StrictEquals((V8Simple::Object const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Object(void * jarg1) {
  V8Simple::Object *arg1 = (V8Simple::Object *) 0 ;
  
  arg1 = (V8Simple::Object *)jarg1; 
  delete arg1;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Array_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Array *arg1 = (V8Simple::Array *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Array *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Array const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Array_Get(void * jarg1, int jarg2) {
  void * jresult ;
  V8Simple::Array *arg1 = (V8Simple::Array *) 0 ;
  int arg2 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Array *)jarg1; 
  arg2 = (int)jarg2; 
  result = (V8Simple::Value *)(arg1)->Get(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Array_Set(void * jarg1, int jarg2, void * jarg3) {
  V8Simple::Array *arg1 = (V8Simple::Array *) 0 ;
  int arg2 ;
  V8Simple::Value *arg3 = (V8Simple::Value *) 0 ;
  
  arg1 = (V8Simple::Array *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (V8Simple::Value *)jarg3; 
  (arg1)->Set(arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_Array_Length(void * jarg1) {
  int jresult ;
  V8Simple::Array *arg1 = (V8Simple::Array *) 0 ;
  int result;
  
  arg1 = (V8Simple::Array *)jarg1; 
  result = (int)(arg1)->Length();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Array_StrictEquals(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  V8Simple::Array *arg1 = (V8Simple::Array *) 0 ;
  V8Simple::Array *arg2 = (V8Simple::Array *) 0 ;
  bool result;
  
  arg1 = (V8Simple::Array *)jarg1; 
  arg2 = (V8Simple::Array *)jarg2; 
  result = (bool)(arg1)->StrictEquals((V8Simple::Array const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Array(void * jarg1) {
  V8Simple::Array *arg1 = (V8Simple::Array *) 0 ;
  
  arg1 = (V8Simple::Array *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Callback() {
  void * jresult ;
  V8Simple::Callback *result = 0 ;
  
  result = (V8Simple::Callback *)new SwigDirector_Callback();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Callback_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Callback const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Callback_GetValueTypeSwigExplicitCallback(void * jarg1) {
  int jresult ;
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Callback const *)arg1)->V8Simple::Callback::GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Callback_Call(void * jarg1, void * jarg2) {
  void * jresult ;
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  V8Simple::UniqueValueVector *arg2 = (V8Simple::UniqueValueVector *) 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  arg2 = (V8Simple::UniqueValueVector *)jarg2; 
  result = (V8Simple::Value *)(arg1)->Call(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Callback_CallSwigExplicitCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  V8Simple::UniqueValueVector *arg2 = (V8Simple::UniqueValueVector *) 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  arg2 = (V8Simple::UniqueValueVector *)jarg2; 
  result = (V8Simple::Value *)(arg1)->V8Simple::Callback::Call(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Callback_Retain(void * jarg1) {
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  (arg1)->Retain();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Callback_RetainSwigExplicitCallback(void * jarg1) {
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  (arg1)->V8Simple::Callback::Retain();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Callback_Release(void * jarg1) {
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  (arg1)->Release();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Callback_ReleaseSwigExplicitCallback(void * jarg1) {
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  (arg1)->V8Simple::Callback::Release();
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Callback(void * jarg1) {
  V8Simple::Callback *arg1 = (V8Simple::Callback *) 0 ;
  
  arg1 = (V8Simple::Callback *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Callback_director_connect(void *objarg, SwigDirector_Callback::SWIG_Callback0_t callback0, SwigDirector_Callback::SWIG_Callback1_t callback1, SwigDirector_Callback::SWIG_Callback2_t callback2, SwigDirector_Callback::SWIG_Callback3_t callback3) {
  V8Simple::Callback *obj = (V8Simple::Callback *)objarg;
  SwigDirector_Callback *director = dynamic_cast<SwigDirector_Callback *>(obj);
  if (director) {
    director->swig_connect_director(callback0, callback1, callback2, callback3);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_External(void * jarg1) {
  void * jresult ;
  void *arg1 = (void *) 0 ;
  V8Simple::External *result = 0 ;
  
  arg1 = (void *)jarg1; 
  result = (V8Simple::External *)new V8Simple::External(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_External_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::External *arg1 = (V8Simple::External *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::External *)jarg1; 
  result = (V8Simple::Type)((V8Simple::External const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_External_GetValue(void * jarg1) {
  void * jresult ;
  V8Simple::External *arg1 = (V8Simple::External *) 0 ;
  void *result = 0 ;
  
  arg1 = (V8Simple::External *)jarg1; 
  result = (void *)(arg1)->GetValue();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_External(void * jarg1) {
  V8Simple::External *arg1 = (V8Simple::External *) 0 ;
  
  arg1 = (V8Simple::External *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ScriptException_GetException(void * jarg1) {
  void * jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (V8Simple::Value *)(arg1)->GetException();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ScriptException_GetErrorMessage(void * jarg1) {
  void * jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (V8Simple::String *)(arg1)->GetErrorMessage();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ScriptException_GetFileName(void * jarg1) {
  void * jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (V8Simple::String *)(arg1)->GetFileName();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ScriptException_GetLineNumber(void * jarg1) {
  int jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  int result;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (int)(arg1)->GetLineNumber();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ScriptException_GetStackTrace(void * jarg1) {
  void * jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (V8Simple::String *)(arg1)->GetStackTrace();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ScriptException_GetSourceLine(void * jarg1) {
  void * jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (V8Simple::String *)(arg1)->GetSourceLine();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ScriptException_Copy(void * jarg1) {
  void * jresult ;
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  V8Simple::ScriptException *result = 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  result = (V8Simple::ScriptException *)(arg1)->Copy();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ScriptException(void * jarg1) {
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ScriptException_Delete(void * jarg1) {
  V8Simple::ScriptException *arg1 = (V8Simple::ScriptException *) 0 ;
  
  arg1 = (V8Simple::ScriptException *)jarg1; 
  (arg1)->Delete();
}


SWIGEXPORT void SWIGSTDCALL CSharp_MessageHandler_Handle(void * jarg1, void * jarg2) {
  V8Simple::MessageHandler *arg1 = (V8Simple::MessageHandler *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  
  arg1 = (V8Simple::MessageHandler *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  (arg1)->Handle((V8Simple::String const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_MessageHandler_HandleSwigExplicitMessageHandler(void * jarg1, void * jarg2) {
  V8Simple::MessageHandler *arg1 = (V8Simple::MessageHandler *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  
  arg1 = (V8Simple::MessageHandler *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  (arg1)->V8Simple::MessageHandler::Handle((V8Simple::String const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MessageHandler(void * jarg1) {
  V8Simple::MessageHandler *arg1 = (V8Simple::MessageHandler *) 0 ;
  
  arg1 = (V8Simple::MessageHandler *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MessageHandler() {
  void * jresult ;
  V8Simple::MessageHandler *result = 0 ;
  
  result = (V8Simple::MessageHandler *)new SwigDirector_MessageHandler();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MessageHandler_director_connect(void *objarg, SwigDirector_MessageHandler::SWIG_Callback0_t callback0) {
  V8Simple::MessageHandler *obj = (V8Simple::MessageHandler *)objarg;
  SwigDirector_MessageHandler *director = dynamic_cast<SwigDirector_MessageHandler *>(obj);
  if (director) {
    director->swig_connect_director(callback0);
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_ScriptExceptionHandler_Handle(void * jarg1, void * jarg2) {
  V8Simple::ScriptExceptionHandler *arg1 = (V8Simple::ScriptExceptionHandler *) 0 ;
  V8Simple::ScriptException *arg2 = 0 ;
  
  arg1 = (V8Simple::ScriptExceptionHandler *)jarg1; 
  arg2 = (V8Simple::ScriptException *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::ScriptException & type is null", 0);
    return ;
  } 
  (arg1)->Handle(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_ScriptExceptionHandler_HandleSwigExplicitScriptExceptionHandler(void * jarg1, void * jarg2) {
  V8Simple::ScriptExceptionHandler *arg1 = (V8Simple::ScriptExceptionHandler *) 0 ;
  V8Simple::ScriptException *arg2 = 0 ;
  
  arg1 = (V8Simple::ScriptExceptionHandler *)jarg1; 
  arg2 = (V8Simple::ScriptException *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::ScriptException & type is null", 0);
    return ;
  } 
  (arg1)->V8Simple::ScriptExceptionHandler::Handle(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ScriptExceptionHandler(void * jarg1) {
  V8Simple::ScriptExceptionHandler *arg1 = (V8Simple::ScriptExceptionHandler *) 0 ;
  
  arg1 = (V8Simple::ScriptExceptionHandler *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ScriptExceptionHandler() {
  void * jresult ;
  V8Simple::ScriptExceptionHandler *result = 0 ;
  
  result = (V8Simple::ScriptExceptionHandler *)new SwigDirector_ScriptExceptionHandler();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ScriptExceptionHandler_director_connect(void *objarg, SwigDirector_ScriptExceptionHandler::SWIG_Callback0_t callback0) {
  V8Simple::ScriptExceptionHandler *obj = (V8Simple::ScriptExceptionHandler *)objarg;
  SwigDirector_ScriptExceptionHandler *director = dynamic_cast<SwigDirector_ScriptExceptionHandler *>(obj);
  if (director) {
    director->swig_connect_director(callback0);
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_ExternalFreer_Free(void * jarg1, void * jarg2) {
  V8Simple::ExternalFreer *arg1 = (V8Simple::ExternalFreer *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (V8Simple::ExternalFreer *)jarg1; 
  arg2 = (void *)jarg2; 
  (arg1)->Free(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_ExternalFreer_FreeSwigExplicitExternalFreer(void * jarg1, void * jarg2) {
  V8Simple::ExternalFreer *arg1 = (V8Simple::ExternalFreer *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (V8Simple::ExternalFreer *)jarg1; 
  arg2 = (void *)jarg2; 
  (arg1)->V8Simple::ExternalFreer::Free(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ExternalFreer(void * jarg1) {
  V8Simple::ExternalFreer *arg1 = (V8Simple::ExternalFreer *) 0 ;
  
  arg1 = (V8Simple::ExternalFreer *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ExternalFreer() {
  void * jresult ;
  V8Simple::ExternalFreer *result = 0 ;
  
  result = (V8Simple::ExternalFreer *)new SwigDirector_ExternalFreer();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ExternalFreer_director_connect(void *objarg, SwigDirector_ExternalFreer::SWIG_Callback0_t callback0) {
  V8Simple::ExternalFreer *obj = (V8Simple::ExternalFreer *)objarg;
  SwigDirector_ExternalFreer *director = dynamic_cast<SwigDirector_ExternalFreer *>(obj);
  if (director) {
    director->swig_connect_director(callback0);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Context(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  V8Simple::ScriptExceptionHandler *arg1 = (V8Simple::ScriptExceptionHandler *) 0 ;
  V8Simple::MessageHandler *arg2 = (V8Simple::MessageHandler *) 0 ;
  V8Simple::ExternalFreer *arg3 = (V8Simple::ExternalFreer *) 0 ;
  V8Simple::Context *result = 0 ;
  
  arg1 = (V8Simple::ScriptExceptionHandler *)jarg1; 
  arg2 = (V8Simple::MessageHandler *)jarg2; 
  arg3 = (V8Simple::ExternalFreer *)jarg3; 
  result = (V8Simple::Context *)new V8Simple::Context(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Context_New(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  V8Simple::ScriptExceptionHandler *arg1 = (V8Simple::ScriptExceptionHandler *) 0 ;
  V8Simple::MessageHandler *arg2 = (V8Simple::MessageHandler *) 0 ;
  V8Simple::ExternalFreer *arg3 = (V8Simple::ExternalFreer *) 0 ;
  V8Simple::Context *result = 0 ;
  
  arg1 = (V8Simple::ScriptExceptionHandler *)jarg1; 
  arg2 = (V8Simple::MessageHandler *)jarg2; 
  arg3 = (V8Simple::ExternalFreer *)jarg3; 
  result = (V8Simple::Context *)V8Simple::Context::New(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Context_Evaluate(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  V8Simple::Context *arg1 = (V8Simple::Context *) 0 ;
  V8Simple::String *arg2 = (V8Simple::String *) 0 ;
  V8Simple::String *arg3 = (V8Simple::String *) 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Context *)jarg1; 
  arg2 = (V8Simple::String *)jarg2; 
  arg3 = (V8Simple::String *)jarg3; 
  result = (V8Simple::Value *)(arg1)->Evaluate((V8Simple::String const *)arg2,(V8Simple::String const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Context_GlobalObject(void * jarg1) {
  void * jresult ;
  V8Simple::Context *arg1 = (V8Simple::Context *) 0 ;
  V8Simple::Object *result = 0 ;
  
  arg1 = (V8Simple::Context *)jarg1; 
  result = (V8Simple::Object *)(arg1)->GlobalObject();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Context_IdleNotificationDeadline(void * jarg1, double jarg2) {
  unsigned int jresult ;
  V8Simple::Context *arg1 = (V8Simple::Context *) 0 ;
  double arg2 ;
  bool result;
  
  arg1 = (V8Simple::Context *)jarg1; 
  arg2 = (double)jarg2; 
  result = (bool)(arg1)->IdleNotificationDeadline(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Context(void * jarg1) {
  V8Simple::Context *arg1 = (V8Simple::Context *) 0 ;
  
  arg1 = (V8Simple::Context *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Context_Delete(void * jarg1) {
  V8Simple::Context *arg1 = (V8Simple::Context *) 0 ;
  
  arg1 = (V8Simple::Context *)jarg1; 
  (arg1)->Delete();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Context_NewExternalArrayBuffer(void * jarg1, int jarg2) {
  void * jresult ;
  void *arg1 = (void *) 0 ;
  int arg2 ;
  V8Simple::Object *result = 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (int)jarg2; 
  result = (V8Simple::Object *)V8Simple::Context::NewExternalArrayBuffer(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_Context_GetVersion() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)V8Simple::Context::GetVersion();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Context_ThrowException(void * jarg1) {
  void * jresult ;
  V8Simple::Value *arg1 = (V8Simple::Value *) 0 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (V8Simple::Value *)jarg1; 
  result = (V8Simple::Value *)V8Simple::Context::ThrowException(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Context_SetDebugMessageHandler(void * jarg1) {
  V8Simple::MessageHandler *arg1 = (V8Simple::MessageHandler *) 0 ;
  
  arg1 = (V8Simple::MessageHandler *)jarg1; 
  V8Simple::Context::SetDebugMessageHandler(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Context_SendDebugCommand(void * jarg1) {
  V8Simple::String *arg1 = (V8Simple::String *) 0 ;
  
  arg1 = (V8Simple::String *)jarg1; 
  V8Simple::Context::SendDebugCommand((V8Simple::String const *)arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Context_ProcessDebugMessages() {
  V8Simple::Context::ProcessDebugMessages();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Int(int jarg1) {
  void * jresult ;
  int *arg1 = 0 ;
  int temp1 ;
  V8Simple::Primitive< int > *result = 0 ;
  
  temp1 = (int)jarg1; 
  arg1 = &temp1; 
  result = (V8Simple::Primitive< int > *)new V8Simple::Primitive< int >((int const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Int_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Primitive< int > *arg1 = (V8Simple::Primitive< int > *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Primitive< int > *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Primitive< int > const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Int_GetValue(void * jarg1) {
  int jresult ;
  V8Simple::Primitive< int > *arg1 = (V8Simple::Primitive< int > *) 0 ;
  int result;
  
  arg1 = (V8Simple::Primitive< int > *)jarg1; 
  result = (int)((V8Simple::Primitive< int > const *)arg1)->GetValue();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Int(void * jarg1) {
  V8Simple::Primitive< int > *arg1 = (V8Simple::Primitive< int > *) 0 ;
  
  arg1 = (V8Simple::Primitive< int > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Double(double jarg1) {
  void * jresult ;
  double *arg1 = 0 ;
  double temp1 ;
  V8Simple::Primitive< double > *result = 0 ;
  
  temp1 = (double)jarg1; 
  arg1 = &temp1; 
  result = (V8Simple::Primitive< double > *)new V8Simple::Primitive< double >((double const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Double_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Primitive< double > *arg1 = (V8Simple::Primitive< double > *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Primitive< double > *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Primitive< double > const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Double_GetValue(void * jarg1) {
  double jresult ;
  V8Simple::Primitive< double > *arg1 = (V8Simple::Primitive< double > *) 0 ;
  double result;
  
  arg1 = (V8Simple::Primitive< double > *)jarg1; 
  result = (double)((V8Simple::Primitive< double > const *)arg1)->GetValue();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Double(void * jarg1) {
  V8Simple::Primitive< double > *arg1 = (V8Simple::Primitive< double > *) 0 ;
  
  arg1 = (V8Simple::Primitive< double > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Bool(unsigned int jarg1) {
  void * jresult ;
  bool *arg1 = 0 ;
  bool temp1 ;
  V8Simple::Primitive< bool > *result = 0 ;
  
  temp1 = jarg1 ? true : false; 
  arg1 = &temp1; 
  result = (V8Simple::Primitive< bool > *)new V8Simple::Primitive< bool >((bool const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Bool_GetValueType(void * jarg1) {
  int jresult ;
  V8Simple::Primitive< bool > *arg1 = (V8Simple::Primitive< bool > *) 0 ;
  V8Simple::Type result;
  
  arg1 = (V8Simple::Primitive< bool > *)jarg1; 
  result = (V8Simple::Type)((V8Simple::Primitive< bool > const *)arg1)->GetValueType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Bool_GetValue(void * jarg1) {
  unsigned int jresult ;
  V8Simple::Primitive< bool > *arg1 = (V8Simple::Primitive< bool > *) 0 ;
  bool result;
  
  arg1 = (V8Simple::Primitive< bool > *)jarg1; 
  result = (bool)((V8Simple::Primitive< bool > const *)arg1)->GetValue();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Bool(void * jarg1) {
  V8Simple::Primitive< bool > *arg1 = (V8Simple::Primitive< bool > *) 0 ;
  
  arg1 = (V8Simple::Primitive< bool > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Clear(void * jarg1) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Add(void * jarg1, void * jarg2) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  V8Simple::String *arg2 = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (V8Simple::String *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::String const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((V8Simple::String const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_StringVector_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  std::vector< V8Simple::String >::size_type result;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  result = ((std::vector< V8Simple::String > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_StringVector_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  std::vector< V8Simple::String >::size_type result;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  result = ((std::vector< V8Simple::String > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  std::vector< V8Simple::String >::size_type arg2 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (std::vector< V8Simple::String >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_StringVector__SWIG_0() {
  void * jresult ;
  std::vector< V8Simple::String > *result = 0 ;
  
  result = (std::vector< V8Simple::String > *)new std::vector< V8Simple::String >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_StringVector__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< V8Simple::String > *arg1 = 0 ;
  std::vector< V8Simple::String > *result = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::String > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< V8Simple::String > *)new std::vector< V8Simple::String >((std::vector< V8Simple::String > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_StringVector__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< V8Simple::String > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< V8Simple::String > *)new_std_vector_Sl_V8Simple_String_Sg___SWIG_2(arg1);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_StringVector_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  SwigValueWrapper< V8Simple::String > result;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_V8Simple_String_Sg__getitemcopy(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = new V8Simple::String((const V8Simple::String &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_StringVector_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  V8Simple::String *result = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (V8Simple::String *) &std_vector_Sl_V8Simple_String_Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  V8Simple::String *arg3 = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (V8Simple::String *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::String const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_V8Simple_String_Sg__setitem(arg1,arg2,(V8Simple::String const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_AddRange(void * jarg1, void * jarg2) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  std::vector< V8Simple::String > *arg2 = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (std::vector< V8Simple::String > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::String > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_V8Simple_String_Sg__AddRange(arg1,(std::vector< V8Simple::String > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_StringVector_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< V8Simple::String > *result = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< V8Simple::String > *)std_vector_Sl_V8Simple_String_Sg__GetRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  V8Simple::String *arg3 = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (V8Simple::String *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::String const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_V8Simple_String_Sg__Insert(arg1,arg2,(V8Simple::String const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  std::vector< V8Simple::String > *arg3 = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< V8Simple::String > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::String > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_V8Simple_String_Sg__InsertRange(arg1,arg2,(std::vector< V8Simple::String > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_RemoveAt(void * jarg1, int jarg2) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_V8Simple_String_Sg__RemoveAt(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_V8Simple_String_Sg__RemoveRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_StringVector_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  V8Simple::String *arg1 = 0 ;
  int arg2 ;
  std::vector< V8Simple::String > *result = 0 ;
  
  arg1 = (V8Simple::String *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "V8Simple::String const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< V8Simple::String > *)std_vector_Sl_V8Simple_String_Sg__Repeat((V8Simple::String const &)*arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Reverse__SWIG_0(void * jarg1) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  std_vector_Sl_V8Simple_String_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_V8Simple_String_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  int arg2 ;
  std::vector< V8Simple::String > *arg3 = 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< V8Simple::String > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::String > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_V8Simple_String_Sg__SetRange(arg1,arg2,(std::vector< V8Simple::String > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_StringVector(void * jarg1) {
  std::vector< V8Simple::String > *arg1 = (std::vector< V8Simple::String > *) 0 ;
  
  arg1 = (std::vector< V8Simple::String > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_Clear(void * jarg1) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_Add(void * jarg1, void * jarg2) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  V8Simple::Value **arg2 = 0 ;
  V8Simple::Value *temp2 = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  temp2 = (V8Simple::Value *)jarg2;
  arg2 = (V8Simple::Value **)&temp2; 
  (arg1)->push_back((V8Simple::Value *const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ValueVector_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  std::vector< V8Simple::Value * >::size_type result;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  result = ((std::vector< V8Simple::Value * > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ValueVector_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  std::vector< V8Simple::Value * >::size_type result;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  result = ((std::vector< V8Simple::Value * > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  std::vector< V8Simple::Value * >::size_type arg2 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (std::vector< V8Simple::Value * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ValueVector__SWIG_0() {
  void * jresult ;
  std::vector< V8Simple::Value * > *result = 0 ;
  
  result = (std::vector< V8Simple::Value * > *)new std::vector< V8Simple::Value * >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ValueVector__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< V8Simple::Value * > *arg1 = 0 ;
  std::vector< V8Simple::Value * > *result = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< V8Simple::Value * > *)new std::vector< V8Simple::Value * >((std::vector< V8Simple::Value * > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ValueVector__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< V8Simple::Value * > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< V8Simple::Value * > *)new_std_vector_Sl_V8Simple_Value_Sm__Sg___SWIG_2(arg1);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ValueVector_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  V8Simple::Value *result = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (V8Simple::Value *)std_vector_Sl_V8Simple_Value_Sm__Sg__getitemcopy(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ValueVector_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  V8Simple::Value **result = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (V8Simple::Value **) &std_vector_Sl_V8Simple_Value_Sm__Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)*result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  V8Simple::Value **arg3 = 0 ;
  V8Simple::Value *temp3 = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  temp3 = (V8Simple::Value *)jarg3;
  arg3 = (V8Simple::Value **)&temp3; 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__setitem(arg1,arg2,(V8Simple::Value *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_AddRange(void * jarg1, void * jarg2) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  std::vector< V8Simple::Value * > *arg2 = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (std::vector< V8Simple::Value * > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_V8Simple_Value_Sm__Sg__AddRange(arg1,(std::vector< V8Simple::Value * > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ValueVector_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< V8Simple::Value * > *result = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< V8Simple::Value * > *)std_vector_Sl_V8Simple_Value_Sm__Sg__GetRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  V8Simple::Value **arg3 = 0 ;
  V8Simple::Value *temp3 = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  temp3 = (V8Simple::Value *)jarg3;
  arg3 = (V8Simple::Value **)&temp3; 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__Insert(arg1,arg2,(V8Simple::Value *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  std::vector< V8Simple::Value * > *arg3 = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< V8Simple::Value * > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__InsertRange(arg1,arg2,(std::vector< V8Simple::Value * > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_RemoveAt(void * jarg1, int jarg2) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__RemoveAt(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__RemoveRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ValueVector_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  V8Simple::Value **arg1 = 0 ;
  int arg2 ;
  V8Simple::Value *temp1 = 0 ;
  std::vector< V8Simple::Value * > *result = 0 ;
  
  temp1 = (V8Simple::Value *)jarg1;
  arg1 = (V8Simple::Value **)&temp1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< V8Simple::Value * > *)std_vector_Sl_V8Simple_Value_Sm__Sg__Repeat((V8Simple::Value *const &)*arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_Reverse__SWIG_0(void * jarg1) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  std_vector_Sl_V8Simple_Value_Sm__Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_ValueVector_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  int arg2 ;
  std::vector< V8Simple::Value * > *arg3 = 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< V8Simple::Value * > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< V8Simple::Value * > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_V8Simple_Value_Sm__Sg__SetRange(arg1,arg2,(std::vector< V8Simple::Value * > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ValueVector_Contains(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  V8Simple::Value **arg2 = 0 ;
  V8Simple::Value *temp2 = 0 ;
  bool result;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  temp2 = (V8Simple::Value *)jarg2;
  arg2 = (V8Simple::Value **)&temp2; 
  result = (bool)std_vector_Sl_V8Simple_Value_Sm__Sg__Contains(arg1,(V8Simple::Value *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ValueVector_IndexOf(void * jarg1, void * jarg2) {
  int jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  V8Simple::Value **arg2 = 0 ;
  V8Simple::Value *temp2 = 0 ;
  int result;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  temp2 = (V8Simple::Value *)jarg2;
  arg2 = (V8Simple::Value **)&temp2; 
  result = (int)std_vector_Sl_V8Simple_Value_Sm__Sg__IndexOf(arg1,(V8Simple::Value *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ValueVector_LastIndexOf(void * jarg1, void * jarg2) {
  int jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  V8Simple::Value **arg2 = 0 ;
  V8Simple::Value *temp2 = 0 ;
  int result;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  temp2 = (V8Simple::Value *)jarg2;
  arg2 = (V8Simple::Value **)&temp2; 
  result = (int)std_vector_Sl_V8Simple_Value_Sm__Sg__LastIndexOf(arg1,(V8Simple::Value *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ValueVector_Remove(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  V8Simple::Value **arg2 = 0 ;
  V8Simple::Value *temp2 = 0 ;
  bool result;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  temp2 = (V8Simple::Value *)jarg2;
  arg2 = (V8Simple::Value **)&temp2; 
  result = (bool)std_vector_Sl_V8Simple_Value_Sm__Sg__Remove(arg1,(V8Simple::Value *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ValueVector(void * jarg1) {
  std::vector< V8Simple::Value * > *arg1 = (std::vector< V8Simple::Value * > *) 0 ;
  
  arg1 = (std::vector< V8Simple::Value * > *)jarg1; 
  delete arg1;
}


SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_String_SWIGUpcast(V8Simple::String *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Function_SWIGUpcast(V8Simple::Function *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Object_SWIGUpcast(V8Simple::Object *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Array_SWIGUpcast(V8Simple::Array *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Callback_SWIGUpcast(V8Simple::Callback *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_External_SWIGUpcast(V8Simple::External *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Int_SWIGUpcast(V8Simple::Primitive< int > *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Double_SWIGUpcast(V8Simple::Primitive< double > *jarg1) {
    return (V8Simple::Value *)jarg1;
}

SWIGEXPORT V8Simple::Value * SWIGSTDCALL CSharp_Bool_SWIGUpcast(V8Simple::Primitive< bool > *jarg1) {
    return (V8Simple::Value *)jarg1;
}

#ifdef __cplusplus
}
#endif

